//
// Created by Dream on 2023/11/16.
//

#ifndef CPP_PRIMERPLUS_STORAGEDURINGSCOPEANDLINKAGE_H
#define CPP_PRIMERPLUS_STORAGEDURINGSCOPEANDLINKAGE_H
void StorageDuringScopeAndLinkageShow();
void Auto();
#endif //CPP_PRIMERPLUS_STORAGEDURINGSCOPEANDLINKAGE_H
