//
// Created by Dream on 2023/11/16.
//

#ifndef CPP_PRIMERPLUS_9_MEMERYMODELANDNAMESPACE_H
#define CPP_PRIMERPLUS_9_MEMERYMODELANDNAMESPACE_H
void memoryModelAndNameSpaceMain();
#endif //CPP_PRIMERPLUS_9_MEMERYMODELANDNAMESPACE_H
